app = "fiber-ir-604bdd"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  FIR_DASHBOARD_DIST = "/app/dashboard/dist"
  FIR_DEMO_SENDER_RPC_URL = "http://fiber-ir-fnn-a-604bdd.internal:18227"
  FIR_DEMO_SENDER_P2P_ADDR = "/dns4/fiber-ir-fnn-a-604bdd.fly.dev/tcp/8228/p2p/Qmf7j9K5GUDsXjrMh86yfAmhhJFTxnNUUpnBRu9rnwN7Tc"
  FIR_STORE_FILE = "/data/incidents.json"
  PORT = "8787"

[http_service]
  internal_port = 8787
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[mounts]]
  source = "fiber_ir_data"
  destination = "/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"
